### ISSUE TITLE
validation items

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL-SIIP/PowerSystems.jl#265]
- [ ] load participation factors sum to 1 in a region/zone (~~CDM~~ TableParsing Parsing)
 - [ ] load time series has values 0-1.0 
 - [x] see #447

**Comment by jd-lara** [comment]
Add to this list: 

- [ ] check active and reactive power values are consistent according to the status field and also the ranges. Requires merging #288 
- [ ] Failing CI in windows due to issues with the name.

**Comment by jd-lara** [comment]
@claytonpbarrows what's the status of this? Can we close the issue or do we have pending items?

**Comment by claytonpbarrows** [comment]
These have not been addressed. There remain a number of validation checks that we could add to this list (e.g. network connectivity)

**Comment by jd-lara** [comment]
@claytonpbarrows I will close this issue since it is stale and hasn't seen change in ver a year.
