### ISSUE TITLE
Check binfo return value from getrf!(B)

### ISSUE THREAD

**Issue by DillonJ** [NREL-SIIP/PowerSystems.jl#447]
It could be an idea to check the binfo return value of getrf!(B). If negative, it means an illegal input value. If positive, it means there are zeros that cause the matrix to be singular indicating islanding or some other problem with the network.

It could be nice to check for this and provide some additional feedback to the user.

I notice there is a #TODO in the code to check for islands, this could also be useful here.

From http://www.netlib.org/lapack/explore-html/dd/d9a/group__double_g_ecomputational_ga0019443faea08275ca60a734d0593e60.html

```
INFO is INTEGER
          = 0:  successful exit
          < 0:  if INFO = -i, the i-th argument had an illegal value
          > 0:  if INFO = i, U(i,i) is exactly zero. The factorization
                has been completed, but the factor U is exactly
                singular, and division by zero will occur if it is used
                to solve a system of equations.
```

**Comment by jd-lara** [comment]
@DillonJ thanks for the suggestion, I added it to #265.
