### ISSUE TITLE
Serialized json can't be loaded in different machine

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/PowerSystems.jl#472]
Currently, the function `to_json` exports the JSON file with an absolute path to the hdf5 file containing the time series. If the files are shared or moved to different files PowerSystem throws an incomprehensible error and require manual modification of the JSON file. 

cc. @rodrigomha

**Comment by daniel-thom** [comment]
The code does not specifically create an absolute path to the HDF5 file in the serialized JSON.  It uses the directory that you provide.

Example 1:
```
to_json(sys, "sys.json")
```
produces `sys.json` in the current directory with an HDF5 file called `sys_time_series_storage.h5` in the current directory.  Paths are relative.

Example 2:
```
to_json(sys, "/tmp/sys.json") 
```
produces `/tmp/sys.json` and `/tmp/sys_time_series_storage.h5`.  The JSON file has an absolute path to the HDF5 file.

It's possible that the code could always serialize a path to the .h5 file that is relative to the requested system JSON file.  It would require some refactoring.

We could certainly make the error more user-friendly.

Does this explain what you saw?  You didn't list any steps, so I am not entirely certain.

**Comment by jd-lara** [comment]
Yes, this is the problem. We should implement a better relative path referencing for the serialization process.
