### ISSUE TITLE
Storage data from RTS-GMLC

### ISSUE THREAD

**Issue by tamas-borbath** [NREL-SIIP/PowerSystems.jl#590]
Hi,

It seems that the data imported from the RTS-GMLC data set is wrong for HydroEnergyReservoir and GenericBattery instances. I could identify two issues but there may be also the third one (see my inflow/initial-storage related constraints).

1. Scale: the storage.csv lists volumes in GWh. After import, the capacity values appear to be too small by a factor of 1000.
2. Base power: This issue affects mostly the hydro instances. On import, the storage.csv>Rating MVA is used to do the per-unit conversion for attributes coming from the storage file. For attributes coming from the gen.csv, the gen.csv>Base MVA column is used. When building the JuMP model the later is used for all. The result is that all the parameters that originate from the storage.csv are wrong in the JuMP model, by about 6% as the Rating MVA is usually 50 while the Base MVA 53. 

Maybe an example can better demonstrate:
The 222_Hydro_1 plant has a max power of 50MW and a reservoir capacity of 1 GWh
The two constraints now look like:
 P__HydroEnergyReservoir_{222_HYDRO_1, 1} ≤ 0.5 **This seems to be correct**
 E__HydroEnergyReservoir_{222_HYDRO_1, 1} ≤ 0.0106 **The right side here should be 10. The magnitude problem is what I listed as issue 1 the inaccuracy problem seems to be issue 2**
E__HydroEnergyReservoir_{222_HYDRO_1, 2} - E__HydroEnergyReservoir_{222_HYDRO_1, 1} + Sp__HydroEnergyReservoir_{222_HYDRO_1, 2} + P__HydroEnergyReservoir_{222_HYDRO_1, 2} = 0.0007238423518714864 **The right side here should be the inflow (0.093) but I haven't figured it out where this goes wrong.**

It would be great if your could look into these problems. Please let me know if I can help with anything.

Thanks,
Tamas

**Comment by tamas-borbath** [comment]
Hi,
Thanks for your quick response!
I rely on the RTS-GMLC repository much like how you use it in the SIIP_Examples.
This attached script (rename it to .jl) [Hydro_storage_RTS.txt](https://github.com/NREL-SIIP/PowerSystems.jl/files/5102218/Hydro_storage_RTS.txt) should allow you reproduce the issue.

Thanks again,
Tamas

**Comment by claytonpbarrows** [comment]
@tamas-borbath thanks. I'm working on improving the hydro and storage parsing now. I'll have a fix soon.

**Comment by claytonpbarrows** [comment]
@tamas-borbath I made some changes to address what I think are the problems, see #594 
A more complete summary with descriptions of the modeling implications follows

**Comment by claytonpbarrows** [comment]
```@meta
EditURL = "<unknown>/../../../Downloads/Hydro_storage_RTS.jl"
```

My Env

```julia
using Pkg
Pkg.status()
```

```
Project SIIPExamples v0.0.1
Status `~/Documents/repos/SIIPExamples.jl/Project.toml`
  [336ed68f] CSV v0.7.7
  [9961bab8] Cbc v0.7.0
  [41994980] D3TypeTrees v0.1.1
  [a93c6f00] DataFrames v0.21.6
  [becb17da] Feather v0.5.6
  [60bf3e95] GLPK v0.13.0
  [2cd47ed4] InfrastructureSystems v0.15.0
  [b6b21f68] Ipopt v0.6.3
  [2535ab7d] JSON2 v0.3.2
  [4076af6c] JuMP v0.21.3
  [98b081ad] Literate v2.5.1
  [47be7bcc] ORCA v0.4.0
  [f0f68f2c] PlotlyJS v0.13.1
  [91a5bcdd] Plots v1.5.8
  [5f7eddb3] PowerGraphics v0.5.2
  [e690365d] PowerSimulations v0.6.3 [`../PowerSimulations.jl`]
  [bcd98974] PowerSystems v0.26.0 [`../PowerSystems.jl`]
  [9e3dc215] TimeSeries v0.18.0
  [f269a46b] TimeZones v1.3.2
  [0f1e0344] WebIO v0.8.14
  [ade2ca70] Dates
  [56ddb016] Logging
  [44cfe95a] Pkg
  [9a3f8284] Random
  [10745b16] Statistics
  [8dfed614] Test

```

# Example from Tamas

```julia
using SIIPExamples

using PowerSystems
using PowerSimulations
using JuMP
using Dates
using DataFrames

using JuMP
using Cbc #solver
const PSI = PowerSimulations
solver = optimizer_with_attributes(Cbc.Optimizer, "logLevel" => 1, "ratioGap" => 0.5)

rts_dir = SIIPExamples.download("https://github.com/GridMod/RTS-GMLC")
rts_src_dir = joinpath(rts_dir, "RTS_Data", "SourceData")
rts_siip_dir = joinpath(rts_dir, "RTS_Data", "FormattedData", "SIIP");
system_base_power = 100.0

rawsys = PowerSystems.PowerSystemTableData(
    rts_src_dir,
    system_base_power,
    joinpath(rts_siip_dir, "user_descriptors.yaml"),
    timeseries_metadata_file = joinpath(rts_siip_dir, "timeseries_pointers.json"),
    generator_mapping_file = joinpath(rts_siip_dir, "generator_mapping.yaml"),
);

sys = System(rawsys; forecast_resolution = Dates.Hour(1), time_series_in_memory=true);

for gen in get_components(HydroEnergyReservoir, sys)
    gen.available=false
end
get_component(HydroEnergyReservoir, sys, "222_HYDRO_1").available=true

branches = Dict{Symbol,DeviceModel}()
devices = Dict(:Hydro => DeviceModel(HydroEnergyReservoir, HydroDispatchReservoirStorage),:Bat => DeviceModel(GenericBattery, BookKeeping))
services = Dict()

template = OperationsProblemTemplate(CopperPlatePowerModel, devices, branches, services);
op_problem = OperationsProblem(GenericOpProblem, template, sys; optimizer = solver, horizon = 2)

PSI.export_op_model(op_problem, "my_op_prob.json")
```

lets look at this reservoir

```julia
reservoir = get_component(HydroEnergyReservoir, sys, "222_HYDRO_1")
```

```
222_HYDRO_1 (PowerSystems.HydroEnergyReservoir):
   name: 222_HYDRO_1
   available: true
   bus: Bell (PowerSystems.Bus)
   active_power: 0.9433962264150944
   reactive_power: -0.13150943396226414
   rating: 0.9905211130872972
   prime_mover: HY
   active_power_limits: (min = 0.0, max = 0.9433962264150944)
   reactive_power_limits: (min = -0.18867924528301888, max = 0.3018867924528302)
   ramp_limits: (up = 0.9433962264150944, down = 0.9433962264150944)
   time_limits: (up = 0.0, down = 0.0)
   operation_cost: PowerSystems.TwoPartCost
   base_power: 53.0
   storage_capacity: 20.0
   inflow: 4.0
   initial_storage: 10.0
   storage_target: 1.0
   conversion_factor: 1.0
   services: 0-element Array{PowerSystems.Service,1}
   dynamic_injector: nothing
   ext: Dict{String,Any}()
   forecasts: InfrastructureSystems.Forecasts: 3
```

the energy limit constraint for period 1 in constraint c_3 in "my_op_problem.json" has an rhs of  0.006008603565516297.
this corresponds to the value of `initial_storage` + the forecasted inflow:

```julia
inflow_ts = values(get_forecast_values(Deterministic, reservoir, Dates.DateTime("2020-01-01T00:00:00"), "get_inflow"))[1:2]
@show get_initial_storage(reservoir) + inflow_ts[1]

# the energy limit constraint for period 2 in constraint c_4 in "my_op_problem.json" had an rhs of  0.0007238423518714864, now it's 0.7238423518714864
```

```
6.008603565516298
```

this corresponds to the value of  the forecasted inflow:

```julia
@show inflow_ts[2]

# the upper bound for the energy variable in period 2 in constraint c10_2 in "my_op_problem.json" had an rhs of 0.0106 now it's 10.6.
```

```
0.7238423518714864
```

this corresponds to the upper limit of the storage capacity of the reservoir:

```julia
@show get_storage_capacity(reservoir)
```

```
10.600000000000001
```

## Notes from Tamas
Mismatch on magnitude as the import treates GWh as MWh
The extra 6% inacuarcy becase in user_descriptors.yaml the Rating MVA is defined as base_power. The reservoir.storage_capacity becomes 1(Max Volume column)/50 (Rating column)= 0.02 *It should be: 1000/53 = 18.86792*

```julia
print("The capacity for 222_HYDRO_1 should be: ",1000/system_base_power," now it's: ",reservoir.storage_capacity*reservoir.base_power/system_base_power)
```

```
The capacity for 222_HYDRO_1 should be: 10.0 now it's: 10.6
```

Same thing happens for reservoir.initial_storage

```julia
print("The initial volume for 222_HYDRO_1 should be: ",500/system_base_power," now it's: ",reservoir.initial_storage*reservoir.base_power/system_base_power)
```

```
The initial volume for 222_HYDRO_1 should be: 5.0 now it's: 5.3
```

The P max however is correct

```julia
print("The P max for 222_HYDRO_1 should be: ",50/system_base_power," and it's correctly: ",reservoir.active_power_limits.max*reservoir.base_power/system_base_power)
```

```
The P max for 222_HYDRO_1 should be: 0.5 and it's correctly: 0.5
```

## Changes made
I implemented unit conversions in the tabular parser to convert GW(h) and kW(h) to MW(h). This requires that the `unit_descriptors.yaml` file has the correct origin units defined. So, I made those changes to RTS-GMLC and the PowerSystemsTestData to correctly reflect the storage column headers.

---

*This page was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*

**Comment by claytonpbarrows** [comment]
see https://github.com/NREL-SIIP/PowerSystemsTestData/pull/36 for an example of how to make the required changes to the `user_descriptors.yaml` file to enable unit conversion

**Comment by jd-lara** [comment]
@claytonpbarrows can we close this?

**Comment by claytonpbarrows** [comment]
I think so. @tamas-borbath if you need further resolution, feel free to re-open.
