### ISSUE TITLE
Add missing Operation Cost to devices 

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/PowerSystems.jl#600]
Should we add cost components for devices such as HydroDispatch and Storage? Currently, these devices don't have costs assigned to them. 

cc. @claytonpbarrows @andrewrosemberg

**Comment by jd-lara** [comment]
Also move `HydroEnergyReservoir` to OperationalCost instead of `TwoPart`?

**Comment by andrewrosemberg** [comment]
From what I see in your code, the difference between `HydroEnergyReservoir` and `HydroDispatch` is the existence of a reservoir attached to it right? and yes, I think both should have a cost attached to it since they can have small but existent operational costs.
