### ISSUE TITLE
Excessive number of getter functions in public API

### ISSUE THREAD

**Issue by raphaelsaavedra** [NREL-SIIP/PowerSystems.jl#603]
The amount of getter functions that are exported by PowerSystems is huge, and it can get overwhelming when you're looking for some of the more obvious ones such as `get_base_power` or `get_base_voltage`.

![image](https://user-images.githubusercontent.com/29098169/92125479-fec0b000-edf6-11ea-9227-3360c94da8cf.png)

In terms of usability of the package, it would be nice to be able to look up the main `get_` functions without getting flooded by functions such as `get_D_45`, `get_L_1d`, `get_T_AA`, which don’t exactly look like they should be public API judging by their names.

**Comment by jd-lara** [comment]
This is a tricky one because we export all getters for all the components we support. The names you don't recognize are dynamic models that make sense to developers of dynamic components

**Comment by daniel-thom** [comment]
I agree that the current design is not scaling well.  It's made worse by the dynamics structs which often have 20+ fields.  It's really a namespace issue. Languages that have methods on structs don't have this problem.

The best Julian approach I'm aware of would be to create a module for each of these type.  For example, all getters and setters for `FiveMassShaft` could be defined like this:
```
module FiveMassShaftModule
get_D_45(value::FiveMassShaft) = value.D_45
end

val = FiveMassShaft()
FiveMassShaftModule.get_D_45(val)
```
We would need a better convention for the module names.

**Comment by raphaelsaavedra** [comment]
@jd-lara I understand that but even then I think having `get_K0`, `get_K1`, ..., `get_K8` is a lot of verbose. Same for `get_T1`, ..., `get_T7` and `get_L_*`. I wonder if there's a nicer interface for these getter functions where they are all under functions such as `get_K`, `get_T`, `get_L` that have an argument pointing to the correct (unexported) function?

**Comment by jd-lara** [comment]
@raphaelsaavedra the only solution is to export only getter functions defined for `System` and those for abstract types. But this will mean that you will still get all of them when doing `PowerSystems. tab` to find a getter for a specific device like in the case of `base_voltage`. 

The naming of the getter for dynamics is consistent with parameter names from Industrial Software, Manufacturers Manuals and IEEE Standards.

**Comment by daniel-thom** [comment]
@raphaelsaavedra For now you're probably better of relying on `methodswith` instead of tab completion.

**Comment by jd-lara** [comment]
I will close this issue since it has no direct solution.
