### ISSUE TITLE
Define equality for components

### ISSUE THREAD

**Issue by raphaelsaavedra** [NREL-SIIP/PowerSystems.jl#604]
It would be useful to have equality defined for components for testing purposes, i.e., simply have `Bus(args...) == Bus(args...)` if `args` are identical (same for `Line`, `PowerLoad`, ...)

```
julia> bus1
krB8Ir2z9txO (Bus):
   number: 1
   name: krB8Ir2z9txO
   bustype: PV
   angle: 0.77995622678973
   magnitude: 0.8707
   voltage_limits: nothing
   base_voltage: 69.0
   area: nothing
   load_zone: nothing
   ext: Dict{String,Any}("zone" => 748,"augmented_name" => "hRPNti829T","area" => 401,"owner" => 5)

julia> bus2 = deepcopy(bus1)
krB8Ir2z9txO (Bus):
   number: 1
   name: krB8Ir2z9txO
   bustype: PV
   angle: 0.77995622678973
   magnitude: 0.8707
   voltage_limits: nothing
   base_voltage: 69.0
   area: nothing
   load_zone: nothing
   ext: Dict{String,Any}("zone" => 748,"augmented_name" => "hRPNti829T","area" => 401,"owner" => 5)

julia> bus1 == bus2
false
```

**Comment by daniel-thom** [comment]
We talked about this a long time ago and punted on overloading `==`.  This could be done automatically handled in Julia but apparently there is still debate on the subject.

For testing purposes we do have the function `IS.compare_values(bus1, bus2)` which would return true in your case.  This could be improved, but as of now it is a best-effort comparison and not guaranteed in all cases.  It would likely handle all the cases you care about.

Something that you might find surprising is that if you created bus1 and bus2 by passing the same arguments to the Bus constructor twice, this test will fail.  The buses would have different UUIDs (stored in their `internal` fields).

Are you using `deepcopy` as part of a workflow to build a System?  If so, that would be problematic because you would have duplicate UUIDs.

**Comment by raphaelsaavedra** [comment]
Oh, that's good to know. No, the `deepcopy` was just to provide the example. Thanks for suggesting `IS.compare_values`, I'll take a look.

**Comment by nickrobinson251** [comment]
AutoHashEquals.jl?

**Comment by daniel-thom** [comment]
Seems like a nice solution.  We would really have to make sure people didn't use components as keys of a `Dict` instead of `IdDict`.  There may be other things to think through.

The only reason that `IS.compare_values` exists is to allow comparison of deserialized objects to their originals and show what values are different.

What is the exact use case that you want to support?  I do want to emphasize that neither of these options would allow `Bus(args...) == Bus(args...)` to return true.

**Comment by jd-lara** [comment]
closing stale issue.

**Comment by nickrobinson251** [comment]
I just ran into this issue when trying to test that two systems x and y created via two different methods result in the same System.

Is there a better alternative, or a short-term workaround, for such a test?

And is there any reason not to define `==` (e.g. as equality of the relevant fields; maybe: data, frequency, bus_numbers, units_settings)?

**Comment by raphaelsaavedra** [comment]
Note that `IS.compare_values` which was suggested above doesn't work either since it accuses differences in the UUIDs.

```julia
julia> x = System(100); y = System(100);

julia> IS.compare_values(x, y)
┌ Error: values do not match
│   T = Base.UUID
│   field_name = :value
│   val1 = 0x56bc61905b2b464ab3cdb553cc97917b
│   val2 = 0xc1250307126d46c1855008bc097041d6
└ @ InfrastructureSystems ~/.julia/packages/InfrastructureSystems/OidS9/src/utils/utils.jl:144
┌ Error: InfrastructureSystemsInternal field=uuid does not match
└ @ InfrastructureSystems ~/.julia/packages/InfrastructureSystems/OidS9/src/internal.jl:115
┌ Error: SystemData field=internal does not match
│   getfield(x, name) = InfrastructureSystems.InfrastructureSystemsInternal(UUID("56bc6190-5b2b-464a-b3cd-b553cc97917b"), nothing, nothing)
│   getfield(y, name) = InfrastructureSystems.InfrastructureSystemsInternal(UUID("c1250307-126d-46c1-8550-08bc097041d6"), nothing, nothing)
└ @ InfrastructureSystems ~/.julia/packages/InfrastructureSystems/OidS9/src/system_data.jl:310
false
```

**Comment by daniel-thom** [comment]
If we were to implement `==` then I think it should compare UUIDs. We support `deepcopy` on the system and components. In that case the UUIDs need to be the same.

It sounds like what you want is a `compare_values` function that excludes the UUID but checks everything else. Is that true?

**Comment by nickrobinson251** [comment]
why would we compare UUID? wouldn't `===` be the command for that?

**Comment by nickrobinson251** [comment]
i also wonder if it would be fair use to use `isequal` to be equality ignoring UUID 🤔 
```julia
help?> isequal
search: isequal issetequal

  isequal(x, y)

  Similar to ==, except for the treatment of floating point numbers and of missing
  values. isequal treats all floating-point NaN values as equal to each other,
  treats -0.0 as unequal to 0.0, and missing as equal to missing. Always returns a
  Bool value.
```

**Comment by daniel-thom** [comment]
I don't think it would appropriate for `===` to return true unless the objects have the same memory address.

```
help?> ===
search: === == !==

  ===(x,y) -> Bool
  ≡(x,y) -> Bool

  Determine whether x and y are identical, in the sense that no program could distinguish them. First the types of x and y are compared. If those are identical, mutable objects are compared by address in memory and immutable objects (such as numbers) are compared by
  contents at the bit level. This function is sometimes called "egal". It always returns a Bool value.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> a = [1, 2]; b = [1, 2];

  julia> a == b
  true

  julia> a === b
  false
```
I think that a strict reading of `==` and `isequal` would require that the UUIDs are equal.

My thought is that a test function that has an option to ignore UUIDs is a pragmatic solution. But I'm still open if you have a different interpretation.

**Comment by nickrobinson251** [comment]
>  a test function that has an option to ignore UUIDs is a pragmatic solution.

Yes, i think this is a valid solution, given that our current use-case is testing. 

I'd prefer as simple as possible an API for this, e.g. `IS.compare_values(x, y, compare_uuids=false)` seems a bit verbose to me. Maybe we could define `==` in a way that respects UUIDs, then `compare_values` doesn't need to `compare_uuids` keyword. 

Also -- thinking further ahead, as a different more advanced feature -- if we're going down the function for testing purposes.... it'd be _really_ nice to get some kind of report on _how_ Systems/Components are different (to help with debugging)

**Comment by daniel-thom** [comment]
I reviewed the code this afternoon. I can implement `compare_values` as discussed above as well as `==`. There will be a few caveats that we can document. I'll open a PR tomorrow.

**Comment by daniel-thom** [comment]
@nickrobinson251 Even though we merged this, feel free to review what I did and make any comments. If we do actually want `==` then we will likely need a different implementation.
