### ISSUE TITLE
Type of `contributing_services` in `add_service!`

### ISSUE THREAD

**Issue by raphaelsaavedra** [NREL-SIIP/PowerSystems.jl#615]
In the definition of `add_service!` for group reserves ([here](https://github.com/NREL-SIIP/PowerSystems.jl/blob/e6bcc29f88d25ad5d7d61d4b893525651c6ee88e/src/base.jl#L404)), I believe `contributing_services::Vector{Service}` should be `contributing_services::Vector{<:Service}`, because the current version forces you to instantiate a vector of the abstract type `Service` instead of allowing vectors of any subtype of `Service`. 

It's also annoying that the error is confusing since the dispatch just leads you to another method and then you simply get an enigmatic `ERROR: ArgumentError: contributing_devices must be of type Device`

**Comment by jd-lara** [comment]
Yes, this is a bug. Thanks for reporting
