### ISSUE TITLE
VariableCost should only accept Tuple{Float64,Float64} or Array{Tuple{Float64,Float64},1}

### ISSUE THREAD

**Issue by andrewrosemberg** [NREL-SIIP/PowerSystems.jl#617]
`VariableCost` should only accept `Tuple{Float64,Float64}` or `Array{Tuple{Float64,Float64},1}`. Currently, it accepts any `Tuple` or `Array{Tuple,1}`, but it errors when creating the system or, if it passes system creation for some reason, it errors when calling build cost functions in PSI.

**Comment by jd-lara** [comment]
Can you provide the StackTrace and an MWE? We have tests for both cases that aren't failing in master.

**Comment by andrewrosemberg** [comment]
I cannot reproduce the error, so It can be something else. Will close this issue for now.
