### ISSUE TITLE
Add example of creating and adding MarketBidCost data

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/PowerSystems.jl#636]
This issue is a response to a request in the slack channel to have an example of the use of `MarketBidCost`.

**Comment by andrewrosemberg** [comment]
Have the examples already been published?

**Comment by jd-lara** [comment]
For now, is in https://nrel-siip.github.io/PowerSystems.jl/latest/modeler_guide/market_bid_cost/ will appear when we do the new release.

**Comment by jd-lara** [comment]
@sourabhdalvi I noticed that the example code runs on an invalid data set. Could you make it not an `@example` block in the docs or make such that the data set is valid? It is not best to display the documentation with error returns.

**Comment by jd-lara** [comment]
closed via #676
