### ISSUE TITLE
Add Documentation 

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/PowerSystems.jl#65]

**Comment by jjstickel** [comment]
Some progress on adding docstrings to structs and constructors were made in https://github.com/NREL/PowerSystems.jl/pull/143 . We'll continue to add docstrings as we work on other issues.

**Comment by claytonpbarrows** [comment]
#82

**Comment by jd-lara** [comment]
This is a good reference about documentation https://www.divio.com/blog/documentation/
I would suggest thinking about using these as guidelines

**Comment by jd-lara** [comment]
Undocumented assumptions used in `PowerSimulations.jl`

- Ramping Limits are given in MW/min
- Min_up/Min_down in Hours or fractions of hour
- Cost in $/MW

**Comment by claytonpbarrows** [comment]
I think Min_up/down should be in fractions of an hour

**Comment by rodrigomha** [comment]
Based on last discussion we are focusing here:
@jd-lara @claytonpbarrows 
- [ ] Create an introduction to basic usage of PSY. Provide references to examples for more details.
- [ ] Some arrangement of the API and docstrings similar to HELICS.

I'll try to do some progress here in my branch 963919da89f676614f2dbc864aa42c0b24177495

**Comment by raphaelsaavedra** [comment]
There are some undocumented unit decisions that I haven't seen mentioned in the current documentation PR or here.

For example, the `active_power` in `PowerLoad` apparently is in pu, but nothing states that, so I initially assumed it would be MW.

**Comment by jd-lara** [comment]
https://github.com/NREL-SIIP/PowerSystems.jl/pull/577 addressed the documentation of the model library. More to follow.

**Comment by andrewrosemberg** [comment]
On [developer/testing](https://github.com/NREL-SIIP/PowerSystems.jl/blob/13f0df76e7bf66ab1128807f8a2f89b291494c3e/docs/src/developer/testing.md) file I got confused. Maybe one more comment could help.

Run a subset of tests in the REPL:

How would one reset ARGS to default after pushing something? If you guys feed this is irrelevant for the time being feel free to ignore.

**Comment by daniel-thom** [comment]
This is really Base.ARGS which is an array, so `empty!(ARGS)`.  We can add a note.
