### ISSUE TITLE
configure_logging not available

### ISSUE THREAD

**Issue by junglegobs** [NREL-SIIP/PowerSystems.jl#691]
The file is there, but when not included maybe, since `PowerSystems.configure_logging` is not defined (I believe this is starting from version 1.0.8 or possibly 1.0.7).

**Comment by jd-lara** [comment]
@junglegobs can you provide some additional information please? I just tested with PowerSystems 1.1.1 and the method is available 

<img width="793" alt="image" src="https://user-images.githubusercontent.com/16385323/104752827-06308800-570c-11eb-910c-df4abdaa5ea8.png">

**Comment by junglegobs** [comment]
Hmmm, this is strange - apparently I'm on `v0.28.1` and I can't upgrade:
```julia
(PH4GEPMs) pkg> up PowerSystems
<stuff>

(PH4GEPMs) pkg> status
Status `~/Desktop/PH4GEPMs/Project.toml`
  [6e4b80f9] BenchmarkTools v0.5.0
  [1e616198] COSMO v0.7.8
  [0a46da34] CSDP v0.7.0
  [336ed68f] CSV v0.7.10
  [9961bab8] Cbc v0.7.1
  [a93c6f00] DataFrames v0.21.8
  [b6b21f68] Ipopt v0.6.5
  [4076af6c] JuMP v0.21.4
  [c36e90e8] PowerModels v0.17.3
  [bcd98974] PowerSystems v0.28.1
  [c46f51b8] ProfileView v0.6.9
  [070f1c60] ProgressiveHedging v0.4.0 `https://github.com/NREL/ProgressiveHedging.jl.git#master`
  [295af30f] Revise v3.1.11
  [c946c3f1] SCS v0.7.1
  [b9a10b5b] SDPA v0.3.0
  [9e3dc215] TimeSeries v0.19.1
  [3a884ed6] UnPack v1.0.2
  [8ba89e20] Distributed
  [56ddb016] Logging
```

**Comment by jd-lara** [comment]
since this is an issue in your environment I will close the issue, but looks like some dependency in your environment is pinning PowerSystems to an old version.
