### ISSUE TITLE
bus angle out of range

### ISSUE THREAD

**Issue by ccookeopen** [NREL-SIIP/PowerSystems.jl#702]
Using the GB grid matpower file from
https://www.maths.ed.ac.uk/optenergy/NetworkData/reducedGB/
When the system is being created, there a number of warnings
The angle limits provided is larger than 3π/2 radians
Running the following gives the output "0.0"
```
  sys=System("GBreducednetwork.m")
  ref_bus=get_bus(sys, 1)
  println(get_angle(ref_bus))
```
Running this subsequently gives "1.7715933"
```
  solve_powerflow!(sys)
  ref_bus=get_bus(sys, 1)
  println(get_angle(ref_bus))
```
This throws an error when the serialized system is deserialized
┌ Error: Invalid range
│   valid_info.struct_name = Bus
│   field_name = angle
│   field_value = 1.7715933
│   valid_range = Dict{String,Any}("max" => 1.571,"min" => -1.571)
│   valid_info.ist_struct = Bus(1, 1, PV, 1.7715933, 1.0, (min = 0.9, max = 1.1), 275.0, Area(1, 0.0, 0.0, 0.0), LoadZone(1, 563.2585999999999, 162.495), Dict{String,Any}("neighbors" => Any[2, 3, 1]))
 
 Changing the slack bus resolves the angle range issue, but with any other bus as the slack bus simulations fail with "NLsolve failed to solve: BoundsError", along with warnings for active and reactive power range boundary limit warnings.

**Comment by jd-lara** [comment]
This is the result of running this system in Matpower: Certainly, there are some buses with large angles. 

![image](https://user-images.githubusercontent.com/16385323/109904127-9d688500-7c51-11eb-8258-aea0cf0e557f.png)

**Comment by jd-lara** [comment]
@ccookeopen I am going to close this issue because it seems the result of the PowerFlow does violate the data quality restrictions we impose on a system. If a similar issue happens again please re-open.
