### ISSUE TITLE
Method with no arguments is redefined here

### ISSUE THREAD

**Issue by kdheepak** [NREL-SIIP/PowerSystems.jl#733]
https://github.com/NREL-SIIP/PowerSystems.jl/blob/3c177de3d954b857271092f4e1a1bb64e6d86d20/src/models/generated/FixedFrequency.jl#L30-L36

**Comment by claytonpbarrows** [comment]
One of the fields cannot have `default` or `internal_default` for the logic to work out. Removing [this line](https://github.com/NREL-SIIP/PowerSystems.jl/blob/master/src/descriptors/power_system_structs.json#L10071) resolves the issue.

**Comment by daniel-thom** [comment]
This case is not covered by the code generator in IS. We should be able to fix it there so that no one accidentally hits it again.
