### ISSUE TITLE
Some arcs counted twice in list/number of system components

### ISSUE THREAD

**Issue by raphaelsaavedra** [NREL-SIIP/PowerSystems.jl#740]
Example:

```
System
======
System Units Base: SYSTEM_BASE
Base Power: 100.0
Base Frequency: 60.0

Components
==========
Num components: 26

8×3 DataFrame
 Row │ ConcreteType                   SuperTypes                         Count 
     │ String                         String                             Int64 
─────┼─────────────────────────────────────────────────────────────────────────
   1 │ Arc                            Topology <: Component <: Infrast…      3
   2 │ Bus                            Topology <: Component <: Infrast…      3
   3 │ Line                           ACBranch <: Branch <: Device <: …      3
   4 │ PhaseShiftingTransformer       ACBranch <: Branch <: Device <: …      1
   5 │ PowerLoad                      StaticLoad <: ElectricLoad <: St…      2
   6 │ StaticReserveGroup{ReserveUp}  Service <: Component <: Infrastr…      3
   7 │ ThermalStandard                ThermalGen <: Generator <: Stati…      2
   8 │ VariableReserve{ReserveUp}     Reserve{ReserveUp} <: Service <:…      9
```

This is a system with 3 lines and one transformer. It should have overall 23 components if we count the services, but for some reason 3 arcs appear listed, resulting in 26 components. I don't know exactly why only 3 arcs are double counted and not all 4.

Another example:

```
System
======
System Units Base: SYSTEM_BASE
Base Power: 100.0
Base Frequency: 60.0

Components
==========
Num components: 199933

8×3 DataFrame
 Row │ ConcreteType                   SuperTypes                         Count 
     │ String                         String                             Int64 
─────┼─────────────────────────────────────────────────────────────────────────
   1 │ Arc                            Topology <: Component <: Infrast…  56077
   2 │ Bus                            Topology <: Component <: Infrast…  45220
   3 │ Line                           ACBranch <: Branch <: Device <: …  44277
   4 │ PhaseShiftingTransformer       ACBranch <: Branch <: Device <: …  15001
   5 │ PowerLoad                      StaticLoad <: ElectricLoad <: St…  38154
   6 │ StaticReserveGroup{ReserveUp}  Service <: Component <: Infrastr…      9
   7 │ ThermalStandard                ThermalGen <: Generator <: Stati…   1159
   8 │ VariableReserve{ReserveUp}     Reserve{ReserveUp} <: Service <:…     36
```

56,077 extra arcs appear in the list for some reason. Note that this does not correspond to all lines and transformers, as that would sum 59,278. Not sure what is going on or if it's something intentional. These arcs didn't use to appear in older versions of PSY.

**Comment by claytonpbarrows** [comment]
`Arc` is simply a (directed) topological connection between `Bus`s, so I while you have 4 `Branch` components,  two of them share the same `Arc`.

**Comment by raphaelsaavedra** [comment]
Oh I see, that makes sense. So any branches between the same two buses will share an Arc. Thanks, that clarifies it. I got confused because Arcs didn't use to be listed among the components.

**Comment by claytonpbarrows** [comment]
Yes, with the added caveat that `Arc`s are directional. So you could have an one connecting bus_1->bus_2 and another bus_2->bus_1.

**Comment by claytonpbarrows** [comment]
Re: the question of previous versions not displaying `Arc` in the `System` summary print...
I believe that at one time we had omitted `Arc` from that summary because they don't really represent physical infrastructure. However, in that sense neither does a `Bus` or `Service`, so I think it makes more sense to just print everything.
