### ISSUE TITLE
Tutorials are not standalone

### ISSUE THREAD

**Issue by odow** [NREL-SIIP/PowerSystems.jl#812]
The tutorials use this `DATA_DIR` variable which is hidden
https://github.com/NREL-SIIP/PowerSystems.jl/blob/eab51ddf29d6d37f62b0c2f160bc7bd632bacee2/docs/src/modeler_guide/modeling_with_JuMP.jl#L20-L21
That makes it a bit confusing
<img width="845" alt="image" src="https://user-images.githubusercontent.com/8177701/133216991-f5b66123-e048-478f-9daf-80403db53013.png">

I assume what's missing in the general 
```
using PowerSystems
DATA_DIR = download(PowerSystems.UtilsData.TestData, folder = pwd())
```

**Comment by jd-lara** [comment]
Thanks for the fix, I will review the rest of the docs to fix this if it happens elsewhere.
