### ISSUE TITLE
Broken Docs

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL-SIIP/PowerSystems.jl#817]
The md isn't rendering properly:
![image](https://user-images.githubusercontent.com/7231396/134423631-0e5d9a40-d6c5-4570-b0f7-78e18f1560eb.png)

DataFrames are really hard to read in dark mode:
![image](https://user-images.githubusercontent.com/7231396/134423759-70c8b4d7-1fe2-4606-aa1e-8d786dfe33f7.png)

**Comment by jd-lara** [comment]
This has been weird since Github enabled the black theme. I am not totally sure how to fix it.
