### ISSUE TITLE
Parsing `storage.csv` in RTS-GMLC

### ISSUE THREAD

**Issue by kibaekkim** [NREL-SIIP/PowerSystems.jl#864]
When parsing the RTS-GMLC data, I am getting the message below:

```shell
ERROR: InfrastructureSystems.DataFormatError("Exactly 1 head storage is required but 313_STORAGE_1 has 2 head storages defined")
```

Please find the code snippet to reproduce and workaround: https://github.com/NREL-SIIP/PowerSystems.jl/issues/862#issue-1159255695

**Comment by daniel-thom** [comment]
Hi @kibaekkim, your RTS-GMLC repository might be out-of-date. This commit should fix your issue: https://github.com/GridMod/RTS-GMLC/commit/4f32e46fff838372c69dcafba30544e09e1c4a9d.

Can you check?

**Comment by kibaekkim** [comment]
I confirm that it works fine with `master` branch. I intentionally used the latest release.
