### ISSUE TITLE
Problem with parsing of PSSE transformer data

### ISSUE THREAD

**Issue by SSte990** [NREL-SIIP/PowerSystems.jl#879]
I have been using PowerSystems.jl to parse data from PSSE .raw files to Julia and I have noticed that the transformer data parsed in Julia does not correspond to the data created by PSSE for power flow. I have found out that the main issue is that the transformer impedance as given in PSSE data might have to be scaled up by factor: (WINDV1/NOMV1)^2 i.e. desired voltage (nominal voltage of the bus)/nominal voltage (voltage on the name plate) of the primary winding. Similar issue was existing in PowerModels.jl:
https://github.com/lanl-ansi/PowerModels.jl/issues/629.

Having in mind this, I would propose that parsing of the transformer data should be double-checked and that the package should also parse WINDV1, NOMV1, WINDV2, NOMV2 as transformer parameters. What would be your thoughts on this?

**Comment by jd-lara** [comment]
We have pretty much the same code in our parser than in power models. We just missed doing this update. If you open a PR with the fix that great. Otherwise I could add the fix over the weekend.

**Comment by SSte990** [comment]
Hej jd-lara,
Thanks for your response. Maybe it would be better if you can add the fix since I am pretty new to GitHub and I am not that familiar with how to do it. I just wanted to report potential bug so that the package can be improved.

**Comment by jd-lara** [comment]
@SSte990 I will look into it soon. 

x-ref to the fix in PowerModels: https://github.com/lanl-ansi/PowerModels.jl/pull/722/files

**Comment by jd-lara** [comment]
@SSte990 I checked the parser and it looks like the fix implemented in PowerModels has already been incorporated. I am not sure what the issue is. Can you confirm which version of PowerSystems.jl are you using?

**Comment by SSte990** [comment]
@jd-lara I am using v1.20.2, the latest stable version. I have looked at the code and I am not certain where is exactly the issue nut I may have some ideas. First to clarify, the data I have is given for coefficients CZ=3 and CW=3. According to PSSE 35.1 manual (PAGV1, Section 4), transformer impedance is calculated as:

Xeq=tj^2 (x_i+x_j)(V_base_j nameplate/V_base desired)^2 (MVA desired/MVA nameplate)

indexes i correspond to "from bus" and indexes j correspond to "to bus". Lines 305-306 from src/io/psse.jl:
305: br_r *= (transformer["NOMV1"]^2 / _get_bus_value(transformer["I"], "base_kv", pm_data)^2) * (pm_data["baseMVA"] / 
 transformer["SBASE1-2"])
306: br_x *= (transformer["NOMV1"]^2 / _get_bus_value(transformer["I"], "base_kv", pm_data)^2) * (pm_data["baseMVA"] / transformer["SBASE1-2"])

Comparing these two I can see that psse.jl is using voltages associated to "from bus" ("NOMV1"; get_bus_value(transformer["I"]) while PSSE manual does not describe this.  (transformer["NOMV1"]^2 / _get_bus_value(transformer["I"], "base_kv", pm_data)^2) is exactly the multiplication factor that is making the difference. 

However, I am not sure how to interpret tj^2 and (V_base_j nameplate/V_base desired)^2  from the manual. 
In my test, the data from PSSE and PowerSystems.jl would match for the following cases:
1. tj^2                          - tap ratio given in pu from the nominal voltage of the j bus; 
    V_base_j nameplate - nominal voltage of the j winding
    V_base desired        -  nominal voltage of the j bus

2. tj^2                          - tap ratio given in pu from the nominal voltage of the j winding; 
    V_base_j nameplate - nominal voltage of the j winding
    V_base desired        -  base voltage for which the input data is given: this should depend on choice of CZ. In case of CZ=3,  
                                        V_base desired = V_base_j nameplate. 

I believe the bug might be in misinterpretation of the pu system of tj^2 and the fact that voltages of "I" side of the transformer are not mentioned in PSSE 35.1 manual. However, I am not entirely sure if this is the problem. What do you think?

**Comment by jd-lara** [comment]
I think what you are proposing makes sense but I need to implement the proposed change and validate so it probably won't be immediate.
