### ISSUE TITLE
Simplify the addition of new structs 

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/PowerSystems.jl#906]
@daniel-thom, this issue summarizes our conversation 

1. automate the code auto generation in CI for users by adding a new struct
2. add a specific workflow such that the users only needs to check in the new struct blob and not modify the larger structs JSON file. 
3. add template for the new structs when users want them. 
4. Improve documentation.

**Comment by jd-lara** [comment]
x-ref to a similar problem: https://github.com/NREL-SIIP/PowerSystems.jl/issues/904

**Comment by daniel-thom** [comment]
@jd-lara Do you consider this fixed?
