### ISSUE TITLE
Allow add_component to reinitialize states on DynamicInjector

### ISSUE THREAD

**Issue by rodrigomha** [NREL-SIIP/PowerSystems.jl#909]
Currently, changing a dynamic component will not update states of the entire dynamic injector.

This could possibly be done in PSY, but it could be also a function in PSID that helps reinitialize only the states. Maybe a substitute_component or something similar can also help.

**Comment by jd-lara** [comment]
close as duplicate of https://github.com/NREL-SIIP/PowerSystems.jl/issues/891
