### ISSUE TITLE
system metadata

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL-SIIP/PowerSystems.jl#915]
- add name #914 
 - description
 - add all this to another file like metatadata.json
 - zip all the system files into system name
 - may want to make considerations for scenarios, shared time series files, and other situations.

**Comment by daniel-thom** [comment]
@claytonpbarrows @jd-lara @sourabhdalvi Can you provide a complete list of what you want in this metadata file?

Some ideas (besides name and description):
- frequency
- component types and counts
- time series counts
- forecast initial times
- forecast total period
- forecast window count
- forecast horizon
- forecast initial timestamp
- forecast interval
- time series resolution

**Comment by sourabhdalvi** [comment]
> @claytonpbarrows @jd-lara @sourabhdalvi Can you provide a complete list of what you want in this metadata file?
> 
> After discussion with Jose
> 
> * name
> * description
> * frequency
> * component types and counts
> * time series types and counts
> * time series resolution

I would like an optional field for
* Timestamp of when the system was created.
* Ability to add an author or creator for the system. (maybe this is a stretch)
* Ability to refer to  the original system from which a case is created (most use cases involve modifying an existing system)

These are some of the meta information that is currently stored in the name of the system.json file, not sure if this is the right place to store them but I think there is a need to preserve this information on multiple projects using SIIP

**Comment by jd-lara** [comment]
@sourabhdalvi This is quite of scope: Ability to refer to the original system from which a case is created (most use cases involve modifying an existing system)
 
we need to develop later a PowerSystemsCaseManager for these features

**Comment by sourabhdalvi** [comment]
That would be awesome capability to have and probably solves most of things I listed

**Comment by jd-lara** [comment]
This comes back to the issue of what is the scope of PSY and what in the scope of a different package. PSY isn't meant to be a data manager, just a data model.

**Comment by daniel-thom** [comment]
How about this as a compromise? Reply with whether you prefer 2a or 2b.
1. Include the items I listed above.
2a. Add everything in the System.ext field to the metadata. This won't work if people are adding non-trivial data to ext.
2b. Assuming ext is huge, add an optional parameter like this `to_json(sys, "my_sys.json", dict_with_my_metadata)`

**Comment by sourabhdalvi** [comment]
I would like 2b but would the system still have the basic metadata you listed above ? or all of that metadata is supposed to be in `dict_with_my_metadata`

**Comment by daniel-thom** [comment]
I'll go with 2b as optional user data. The rest of it will always be there.

New question: How should time series resolution be displayed? Some options:
```
1. "time_series_resolution": "60 minutes"
2. "time_series_resolution_minutes": 60
```
