### ISSUE TITLE
Displaying systems with pretty tables in logger

### ISSUE THREAD

**Issue by m-bossart** [NREL-SIIP/PowerSystems.jl#924]
It would be nice to display things nicely within logging statements. 
Currently, 
```
sys = System(100.0)
display(sys)  # shows the pretty tables output summarizing the system. 
@info sys    # does not. 
```

**Comment by jd-lara** [comment]
@daniel-thom it seems that to implement this we need to add some methods for the logger io

**Comment by jd-lara** [comment]
This issue will be resolve with the addition of a metadata file in PSY 2.0
