### ISSUE TITLE
get_time_series methods don't convert time series values to natural units for Services

### ISSUE THREAD

**Issue by sourabhdalvi** [NREL-SIIP/PowerSystems.jl#972]
Seems like when retrieving time series values when the unit setting is set to "natural_units" are not converted, other devices like PowerLoads have time series  converted to natural units but not for services. attached an example for this on the RTS
For reserves :
![image](https://user-images.githubusercontent.com/18898869/220243300-a1799873-5c66-480d-a5c4-91c2f0f774c6.png)
For Loads :
![image](https://user-images.githubusercontent.com/18898869/220243626-49ca6e4b-5588-4566-9ea4-9efb612a6788.png)

**Comment by sourabhdalvi** [comment]
conversion is not happening on the reserve fields as well 
![image](https://user-images.githubusercontent.com/18898869/220244265-850efeb4-2aa7-4034-84ee-ab07eb4a168b.png)

**Comment by jd-lara** [comment]
I don't know if we ever implemented the methods to get this done.

**Comment by jd-lara** [comment]
getter functions with mva base conversion needs to be implemented.
